### ISSUE TITLE
Pull proper commits from catalyst client and remove the EVM modifications.

### ISSUE THREAD

**Issue by blazejkrzak** [lukso-network/pandora-execution-engine#47]
Pull proper commits from catalyst client and remove the EVM modifications.

**Comment by blazejkrzak** [comment]
@atif-konasl Why would we do anything in catalyst? We have decided to fork raw geth 1.10.0

**Comment by atif-konasl** [comment]
@blazejkrzak Yes you are right. We will start from geth 1.10.0. We need some commits from catalyst repo like -
- backend: make the eth2 api public
- Add txpool.processtxs flag allowing for process txs upon node launch
- cmd/geth: add the catalyst command

If we need anything necessary from their commits then we can pull their commits.

**Comment by blazejkrzak** [comment]
Master of this repo is already at geth 1.10.0
