### ISSUE TITLE
Create ci/cd flow to deploy changes

### ISSUE THREAD

**Issue by blazejkrzak** [lukso-network/pandora-execution-engine#6]

**Comment by blazejkrzak** [comment]
@frozeman Please help us with access and other stuff.
I think we should schedule a small talk how we would like to achieve this goal

**Comment by blazejkrzak** [comment]
I suggest travisCi, or circleCI 
we have already basic code here:
https://github.com/brave-experiments/Mjolnir/blob/master/.travis.yml

@frozeman maybe you have some directions for us?




I would deploy it as realease in gh,
during one step of ci/cd I would deploy new binary of geth to the l15 node 2, and create node 3 which would be only archive node.
Then I would curl jsonrpc for a health check.
More complex solutions IMHO are not needed right now

**Comment by frozeman** [comment]
On which repo you want to add the Travis job?
We have to make sure to stay upstream compatible. This would make more sense in the l15 repo

Kind regards,
Fabian

**Comment by blazejkrzak** [comment]
Yeah, l15 seems the best choice and as argument it would fetch branch from lukso-network/go-ethereum

**Comment by mxmar** [comment]
Moved to: https://github.com/lukso-network/lukso-orchestrator/issues/13
